
#' Summarize pairwise clustering
#'
#' Function to summarize pairwise clustering
#'
#' @param obj fitted model object
#'
#' @return list of pairwise clustering probability matrices for beta and theta.
#'
#' @export
pairwise_clusters <- function(obj){


  dims <- dim(obj$Zbeta)
  matbetay <- matthetay <- matbetax <- matthetax <- matrix(NA,nrow=dims[1]*dims[2],ncol=dims[1]*dims[2])
  for(kk in 1:dims[1]){
    for(jj in 1:dims[2]){
      for(kk2 in 1:dims[1]){
        for(jj2 in 1:dims[2]){
          ## ordering by y
          matbetay[(kk-1)*dims[2]+jj,(kk2-1)*dims[2]+jj2] <- round(100*mean(obj$Zbeta[kk,jj,]==obj$Zbeta[kk2,jj2,]))
          matthetay[(kk-1)*dims[2]+jj,(kk2-1)*dims[2]+jj2] <- round(100*mean(obj$Ztheta[kk,jj,]==obj$Ztheta[kk2,jj2,]))
          ## ordering by x
          matbetax[(jj-1)*dims[1]+kk,(jj2-1)*dims[1]+kk2] <- round(100*mean(obj$Zbeta[kk,jj,]==obj$Zbeta[kk2,jj2,]))
          matthetax[(jj-1)*dims[1]+kk,(jj2-1)*dims[1]+kk2] <- round(100*mean(obj$Ztheta[kk,jj,]==obj$Ztheta[kk2,jj2,]))
        }
      }

    }
  }

  rownames(matbetay) <- colnames(matbetay) <- rownames(matthetay) <- colnames(matthetay) <-
    paste0("y",rep(1:dims[1],each=dims[2]),"x",rep(1:dims[2],dims[1]))
  rownames(matbetax) <- colnames(matbetax) <- rownames(matthetax) <- colnames(matthetax) <-
    paste0("x",rep(1:dims[2],each=dims[1]),"y",rep(1:dims[1],dims[2]))

  return(list(beta_y=matbetay,theta_y=matthetay, ## order by y
              beta_x=matbetax,theta_x=matthetax)) ## order by x
}







#' Summarize pairwise clustering
#'
#' Function to summarize pairwise clustering
#'
#' @param heat heat matrix (matrix of pairwise clustering probabilities) generated by 'pairwise_clusters'
#'
#' @return heatplot of pairwise clustering probabilities
#'
#' @export
make_heatplot <- function(heat){
  heat <- rbind(heat,0) ## add a 0 to have a standard baseline color (removed later)
  heatplot <- ggplot2::ggplot(data = reshape::melt(heat), ggplot2::aes(x=X1, y=X2,fill=value)) +
    ggplot2::geom_tile()+
    ggplot2::scale_fill_gradientn(colours = c("white", "coral4"),values = c(0,1))+
    ggplot2::geom_text(ggplot2::aes(X1, X2, label = value),color = "white", size = 4)+
    ggplot2::labs(x="", y="")+
    ggplot2::scale_y_discrete(limits=rev)+
    ggplot2::scale_x_discrete(position = 'top',
                     limits=c(colnames(heat)))+
    ggplot2::guides(fill="none")+
    ggplot2::theme(plot.margin = ggplot2::unit(c(-0.5,0, 0.5, 0), "cm"),
          panel.background = ggplot2::element_blank())+
    ggplot2::ggtitle("")

  return(heatplot)
}









